targets:
  $default:
    builders:
      mek_assets:
        options:
          output_directory: lib/src
          output_file: r.g.dart
          single_assets_class: R
          assets:
            assets/images/: RandomImages
            assets/json/: false